### ISSUE TITLE
请问这个组件里面暴露出来的有点击完成的回调函数吗？

### ISSUE THREAD

**Issue by XueChengxi** [chenruifu/lunarDateSelection#2]
最近在使用您的这个组件，但是也遇到了一些问题，我们是在Vue 项目中使用的您的组件，将您的组件进行了单独的封装，但是在父组件中却怎么也无法实时的拿到input 的 value值，请问在您的组件中有成功的回调函数吗？该如何使用？望解答，谢谢！

**Comment by chenruifu** [comment]
你可以在结果回调那边重构下
![image](https://user-images.githubusercontent.com/19771516/48453477-871f2c80-e7ee-11e8-997a-4b00ba66fdff.png)

**Comment by wx1096** [comment]
请问一下  在滑动过程中快速点击 会导致 日期回弹失败
![bz ywm f 62l3 a _dq](https://user-images.githubusercontent.com/37656319/51102608-95072300-181a-11e9-862b-c7f6c8361303.png)
选择日期就会出错 怎么能解决！谢谢

**Comment by XueChengxi** [comment]
> 你可以在结果回调那边重构下
> ![image](https://user-images.githubusercontent.com/19771516/48453477-871f2c80-e7ee-11e8-997a-4b00ba66fdff.png)

如何进行赋值呢？

**Comment by chennxu** [comment]
您好，您这个可以拓展下年份吗？1900-2050年的

**Comment by chenruifu** [comment]
占不做处理

**Comment by lp13762436965** [comment]
请问有相关的回调函数嘛
