### ISSUE TITLE
修改时间区间会报错

### ISSUE THREAD

**Issue by webxiajun** [chenruifu/lunarDateSelection#5]
这边实际场景需要用到的年份时间区间是; 1931-2020, 所以自己尝试自行修改代码，修改点主要如下：
1. var FIRSTYEAR = 1931;    
2. this.minY = 1931;
3. new tagLunarCal 的时候增加 1931到1939的，具体如下：
    new tagLunarCal(47, 0, 3, 5, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0), /* 1931 */
    new tagLunarCal(36, 0, 4, 57, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0), /* 1932 */
    new tagLunarCal(25, 5, 6, 3, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1), /* 1933 */
    new tagLunarCal(44, 0, 0, 8, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0), /* 1934 */
    new tagLunarCal(34, 0, 1, 13, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0), /* 1935 */
    new tagLunarCal(23, 3, 2, 18, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0), /* 1936 */
    new tagLunarCal(41, 0, 4, 24, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0), 0, /* 1937 */
    new tagLunarCal(30, 7, 5, 29, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1), /* 1938 */
    new tagLunarCal(49, 0, 6, 34, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0), /* 1939 */

很奇怪，如果当年的农历没有闰月，最后一个m13参数这边填的是0还是1， 我目前全部填0，然后尝试运行，会报错

**Comment by chenruifu** [comment]
我记得应该是还得考虑到日期的最大最小值是否正确

**Comment by webxiajun** [comment]
这边方便微信加你聊下吗，急需这个组件













在 2020-05-08 13:52:04，"羯瑞" <notifications@github.com> 写道：

我记得应该是还得考虑到日期的最大最小值是否正确

**Comment by webxiajun** [comment]
我微信号xiaxiaojun_victor










在 2020-05-08 13:52:04，"羯瑞" <notifications@github.com> 写道：

我记得应该是还得考虑到日期的最大最小值是否正确

**Comment by chenruifu** [comment]
123
